"""策略版本与参数 — 离线构建脚本与前端展示共用。"""

STRATEGY_VERSION = "v1.2.0"
STRATEGY_NAME = "港股一波流策略（突破+跟踪止损）"

# 上一版本基线（实验室对比用）
PREVIOUS_VERSION = "v1.1.0"
PREVIOUS_BASELINE = {
    "winRate": 38.5,
    "expectancy": -0.13,
    "profitFactor": 0.95,
    "maxDrawdown": -17.18,
}

# 评分阈值
BUY_SCORE = 75
WATCH_SCORE = 62
BREAKOUT_SCORE_MIN = 68

# Regime：个股与恒指均需在长期均线之上才做多
REQUIRE_ABOVE_MA200 = True
REQUIRE_BENCH_ABOVE_MA200 = True
REQUIRE_BULL_MARKET = True
MAX_RSI_ENTRY = 75
MIN_RELATIVE_STRENGTH = 0.0
REQUIRE_MACD_POSITIVE = False

# 平台突破入场
BREAKOUT_LOOKBACK = 40
BREAKOUT_VOLUME_RATIO = 1.5

# 风控与出场
RISK_PER_TRADE_PCT = 2.0
REWARD_RISK_RATIO = 3.0
MAX_POSITION_PCT = 25.0
ATR_STOP_INITIAL = 2.5
ATR_TRAILING = 3.0
ATR_BREAKEVEN_MULT = 1.0
USE_TRAILING_STOP = True

# 强趋势（保留兼容）
ATR_STOP_STRONG = 2.0
ATR_STOP_NORMAL = 2.5

# 信号生命周期
SIGNAL_MAX_HOLD_DAYS = 60

# 模拟账户（仅 buy 信号开仓，专注小米）
PAPER_SYMBOL = "1810.HK"
PAPER_SYMBOL_NAME = "小米集团"
PAPER_SYMBOL_MARKET = "港股"
PAPER_SYMBOL_HK_CODE = "01810"
PAPER_INITIAL_CASH = 1_000_000.0
PAPER_MAX_POSITIONS = 1
PAPER_BUY_ONLY = True
PAPER_IPO_DATE = "2018-07-09"

# 回测
BACKTEST_PERIOD = "1y"
BACKTEST_HOLD_DAYS = 60
BACKTEST_COOLDOWN_BARS = 5
