"""策略版本与参数 — 离线构建脚本与前端展示共用。"""

STRATEGY_VERSION = "v1.1.0"
STRATEGY_NAME = "多因子趋势策略（强化风控）"

# 上一版本基线（实验室对比用）
PREVIOUS_VERSION = "v1.0.0"
PREVIOUS_BASELINE = {
    "winRate": 29.0,
    "expectancy": -1.36,
    "profitFactor": 0.59,
    "maxDrawdown": -37.82,
}

# 评分阈值（v1.1 提高买入门槛）
BUY_SCORE = 78
WATCH_SCORE = 62

# 硬过滤
REQUIRE_BULL_MARKET = True
MAX_RSI_ENTRY = 72
MIN_RELATIVE_STRENGTH = 0.0
REQUIRE_MACD_POSITIVE = True

# 风控
RISK_PER_TRADE_PCT = 2.0
REWARD_RISK_RATIO = 2.0
MAX_POSITION_PCT = 25.0
ATR_STOP_STRONG = 1.5
ATR_STOP_NORMAL = 2.0

# 信号生命周期
SIGNAL_MAX_HOLD_DAYS = 25

# 模拟账户（仅 buy 信号开仓，专注小米）
PAPER_SYMBOL = "1810.HK"
PAPER_SYMBOL_NAME = "小米集团"
PAPER_SYMBOL_MARKET = "港股"
PAPER_SYMBOL_HK_CODE = "01810"
PAPER_INITIAL_CASH = 1_000_000.0
PAPER_MAX_POSITIONS = 1
PAPER_BUY_ONLY = True
PAPER_IPO_DATE = "2018-07-09"  # 港交所挂牌日

# 回测
BACKTEST_PERIOD = "1y"
BACKTEST_HOLD_DAYS = 25
BACKTEST_COOLDOWN_BARS = 10
